name: New user addition to devspace
description: File a new issue
title: "Issue: "
labels: [bug, question]
body:
  - type: input
    id: alias
    attributes:
      label: Alias
      description: Enter your alias which is composed of your FirstName followed by your LastName initial. Example Alias for employee "John Doe" would be "johnd"
      placeholder: e.g. johnd
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      description: Enter your @harness.io email address.
      placeholder: you@harness.io
    validations:
      required: true

  - type: dropdown
    id: cluster
    attributes:
      label: Cluster
      description: Choose a cluster.
      options:
        - scm-team
        - iac-team
        - idp-team
        - srm-team
        - chaos-team
        - qa-test
        - smp-weekly-signoff
        - pl-team
        - plg-team
        - cet-team
        - sei-team
        - ff-team
        - ssca-team
        - sre
        - sre-team
        - pl-team-istio
        - sto-team
        - scale-cluster
        - code-team
        - infra
        - ccm-team
        - cd-team
        - bt-team
        - ci-team


    validations:
      required: true

  - type: dropdown
    id: team
    attributes:
      label: Team
      description: Choose your team.
      options:
        - cet-team-delegate
        - pl-team
        - code-team-delegate
        - idp-team-delegate
        - CD
        - gtm-team
        - SRE
        - ccm-team-delegate
        - BT
        - FF
        - CCM
        - iac-team-delegate
        - CHAOS
        - chaos-team-delegate
        - SEI
        - ssca-team-delegate
        - scale-cluster
        - IE-DEV-TEST
        - smp-team
        - srm-team-delegate
        - PL
        - pl-team-istio
        - SCM
        - plg-team-delegate
        - STO
        - CI
        
    validations:
      required: true
