name: Onboarding New Developer

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        persist-credentials: true

    - name: Set Git Config
      run: |
        git config user.name "Actions service account"
        git config user.email "no-reply@github.com"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Python Dependencies
      run: |
        pip install PyYAML
        pip install requests

    - name: Print Alias
      run: |
        echo "Alias is ${{ steps.extract_copy_modify.outputs.alias }}"



    - name: Extract, Copy, and Modify
      id: extract_copy_modify
      run: |
        python .github/scripts/extract_copy_modify.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This will set the token for the script to use

    - name: Create New Branch
      run: |
        git checkout -b ${{ steps.extract_copy_modify.outputs.alias }}

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Setup dev environment for ${{ steps.extract_copy_modify.outputs.alias }}"
        git push origin main

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "New Developer Setup: ${{ steps.extract_copy_modify.outputs.alias }}"
        pr_body: "Automated setup for new developer ${{ steps.extract_copy_modify.outputs.alias }}."
        destination_branch: "main"